"""Migration to v1.1.1

Revision ID: 78195eb9d1db
Revises: 375fa26249aa
Create Date: 2021-11-15 21:43:18.323756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78195eb9d1db'
down_revision = '375fa26249aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'last_seen',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'last_seen',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
